[project]
name = "wagtail-prose-editor-images"
version = "0.1.2"
description = "Wagtail Image Chooser integration for django-prose-editor."
readme = "README.md"
authors = [{ name = "Vladimir Tarasov" }]
license = { text = "MIT" }
classifiers = [
    "Framework :: Django",
    "Framework :: Wagtail",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "wagtail>=6.0",
    "django-prose-editor>=0.26",
]

[project.urls]
Home = "https://github.com/vovansrnd/wagtail-prose-editor-images"
Source = "https://github.com/vovansrnd/wagtail-prose-editor-images"
Issues = "https://github.com/vovansrnd/wagtail-prose-editor-images/issues"
